[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install -r dashboard/backend/requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && cd dashboard/backend && python app.py"