[build]
cmd = "cd dashboard/frontend && npm install && npm run build && cd ../backend && pip install -r requirements.txt"

[start]
cmd = "cd dashboard/backend && python app.py"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
NODE_VERSION = "18"