[phases.setup]
nixPkgs = ["nodejs-18_x", "python311"]

[phases.install]
cmd = "cd dashboard/frontend && npm ci"

[phases.build]
cmd = "cd dashboard/frontend && npm run build && cd ../backend && pip install -r requirements.txt"

[start]
cmd = "cd dashboard/backend && python app.py"